### ISSUE TITLE
Legacy corrector has been deprecated

### ISSUE THREAD

**Issue by leoarnold** [r7kamura/templatecop#11]
```
/home/user/.rvm/gems/ruby-3.3.4@project/gems/rubocop-1.65.1/lib/rubocop/cop/legacy/corrector.rb:22: warning: `Corrector#corrections` is deprecated. Open an issue if you have a valid usecase.
See https://docs.rubocop.org/rubocop/v1_upgrade_notes.html
```

**Comment by r7kamura** [comment]
Thanks for the report. I have not looked at it in detail, but I was not aware that there was any kind of deprecation warning.

I am thinking of deprecating this gem soon.
When I created this gem, RuboCop did not have an API for this kind of plugin, but now that it has been added on a trial basis, I have created new gems such as rubocop-erb and rubocop-haml. I'm planning to encourage migration to that.
