### ISSUE TITLE
Merge priority for RuboCop configurations

### ISSUE THREAD

**Issue by nobuyo** [r7kamura/templatecop#3]
Thank you for fixing the default settings for slimcop the other day! (https://github.com/r7kamura/slimcop/commit/117e8a6a0fc0b2662cae9189cc9b34a0a42f7a3e)

## Problem

If the rails application's `.rubocop.yml` contains conflicting cop settings, it will override the default.yml setting and continue to cause syntax errors.

```yml
// .rubocop.yml in Rails application
...

Layout/FirstArrayElementLineBreak:
  Enabled: true // <- should be overwritten in slimcop

...
```

For example, `Layout/FirstArrayElementLineBreak` is a valid cop for pure ruby code,
and therefore, I think the priority for templatecop should be the `default.yml` of slimcop, etc. rather than `.rubocop.yml`.

It seems to be related to this implementation:
- https://github.com/r7kamura/templatecop/blob/cd7854916d875b979ef7e6d234f365336bd3c3a5/lib/templatecop/rubo_cop_config_generator.rb#L39-L43

## Expected behavior
I would expect that slimcop will run according to the `default.yml` setting related to keeping syntax at least.

## Environments

- slimcop 0.16.0
- templatecop 0.2.2
- slimi 0.7.2

**Comment by r7kamura** [comment]
> For example, `Layout/FirstArrayElementLineBreak` is a valid cop for pure ruby code,
> and therefore, I think the priority for templatecop should be the `default.yml` of slimcop, etc. rather than `.rubocop.yml`.

No, I don't think so. The settings in default.yml are not always correct, and sometimes the user may want to override them. If we make default.yml always take precedence, then users will not be able to override the settings by their custom config.

If you want to enable Layout/FirstArrayElementLineBreak in your .rubocop.yml but want to disable it on Slimcop, you might want to have .slimcop.yml and disable it like this:

```yaml
# .slimcop.yml
inherit_from: .rubocop.yml

Layout/FirstArrayElementLineBreak:
  Enabled: false
```

**Comment by nobuyo** [comment]
I see. I create an issue because I thought it was critical that the syntax was broken, but I should have read the code thoroughly before I did it 🙏 

Thank you so much.
